### ISSUE TITLE
Parallel "installation" of Reactions and Reactions+ crashes Bludit

### ISSUE THREAD

**Issue by DigitalAssasin** [pytesNET/reactions#5]
Hi,

I was using the "old" reactions plugin for a while now. With the new version I followed your setup instructions and copied the reactions-plus folder to my Bludit setup without disabling or deleting the old reactions plugin directory. As a result the website throws a 500 error.

I had to remove the new directory and disable and remove the old plugin version. Afterwards I was able to setup the new plugin version as in your installation guide.

Maybe you should mention this point in your guide for existing users.

Regards,

Christian

**Comment by SamBrishes** [comment]
Hellow,

sorry for this misunderstanding. The installation instructions described in the readme is just for the first-time installation. I added an "Upgrade Instructions" section directly below. 

In short: You just need to replace the old files with the new ones (regardless i you're using Reactions or Reactions+), the upgrade process itself is done automatically. And you can't use Reactions and Reactions+ next to each other, since they are using the same Plugin Class name.

Thanks for your notice.

Sam.
